/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AttributeEditorWidget: typeof import('./components/items/AttributeEditorWidget.vue')['default']
    GameObjectEditor: typeof import('./components/GameObjectEditor.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ItemEditor: typeof import('./components/items/ItemEditor.vue')['default']
    ItemList: typeof import('./components/items/ItemList.vue')['default']
    ModifiableEditorWidget: typeof import('./components/items/ModifiableEditorWidget.vue')['default']
    ModifierEditorWidget: typeof import('./components/items/ModifierEditorWidget.vue')['default']
    ModifierList: typeof import('./components/modifiers/ModifierList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
