/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/control': RouteRecordInfo<'/control', '/control', Record<never, never>, Record<never, never>>,
    '/items/[[id]]': RouteRecordInfo<'/items/[[id]]', '/items/:id?', { id?: ParamValueZeroOrOne<true> }, { id?: ParamValueZeroOrOne<false> }>,
    '/items/list': RouteRecordInfo<'/items/list', '/items/list', Record<never, never>, Record<never, never>>,
    '/modifiers/[[id]]': RouteRecordInfo<'/modifiers/[[id]]', '/modifiers/:id?', { id?: ParamValueZeroOrOne<true> }, { id?: ParamValueZeroOrOne<false> }>,
    '/playground': RouteRecordInfo<'/playground', '/playground', Record<never, never>, Record<never, never>>,
  }
}
